export const PATH = Object.freeze({
  MAIN: '/',
  PRICE: '/pricing',
  LOGIN: '/login',
  SIGN_UP: '/signup',
  SOCIAL_SIGN_UP: '/social/signup',
  FORGET_PASSWORD: '/password/forget',
  RESET_PASSWORD: '/password/reset'
});

export const ADMIN_PATH = Object.freeze({
  SCREENS: '/screens',
  SCHEDULES: '/schedules',
  NEW_SCHEDULES: '/schedules/new',
  DETAIL_SCHEDULES: '/schedules/:id',
  EDIT_SCHEDULES: '/schedules/edit/:id',
  SCREENS_SCHEDULES: '/schedules/screen/:id',
  PLAYLISTS: '/playlists',
  NEW_PLAYLISTS: '/playlists/new',
  EDIT_PLAYLISTS: '/playlists/edit/:id',
  DETAIL_PLAYLISTS: '/playlists/:id',
  SCREENS_PLAYLISTS: '/playlists/screen/:id',
  CANVAS: '/canvas',
  NEW_CANVAS: '/canvas/new',
  TEMPLATE_CANVAS: '/canvas/template',
  DETAIL_CANVAS: '/canvas/:id',
  MEDIA: '/media',
  MEDIA_FILE: '/media/file/:id',
  MEDIA_FOLDER_FILE: '/media/file/:folderId/:id',
  MEDIA_FOLDER: '/media/folder/:id',
  INQUIRY: '/inquiry',
  SETTINGS_TEAM: '/settings/team',
  SETTINGS_ROLES: '/settings/roles',
  ACCOUNT_PROFILE: '/account/profile',
  ACCOUNT_BUSINESS: '/account/business',
  ACCOUNT_PLAN: '/account/plan',
  ACCOUNT_BILLING: '/account/billing',
  ACCOUNT_PAYMENT: '/account/payment',
  ACCOUNT_PLAN_CANCEL: '/account/plan/cancel/:id',
  ACCOUNT_BYE: '/account/bye',
  PAYMENT_SUCCESS: '/payment/success',
  PAYMENT_FAIL: '/payment/fail',
  PAYMENT_CANCEL: '/payment/cancel',
  PAYMENT_SUBSCRIPTION: '/payment/subscription'
});
